"""
Script to populate the database with mock book data for Burt's Bookshelf
"""

import os
import django
from datetime import date

# Setup Django environment
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "burts_books.settings")
django.setup()

from bookstore.models import Book

# Clear existing books
Book.objects.all().delete()

# Mock book data
books_data = [
    # Fiction Books
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "description": "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780525559474",
        "publication_date": date(2020, 8, 13),
        "in_stock": True,
    },
    {
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "description": 'For years, rumors of the "Marsh Girl" have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark.',
        "price": 15.99,
        "category": "fiction",
        "isbn": "9780735219090",
        "publication_date": date(2018, 8, 14),
        "in_stock": True,
    },
    {
        "title": "The Seven Husbands of Evelyn Hugo",
        "author": "Taylor Jenkins Reid",
        "description": "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.",
        "price": 17.99,
        "category": "fiction",
        "isbn": "9781501161933",
        "publication_date": date(2017, 6, 13),
        "in_stock": True,
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "description": "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.",
        "price": 18.99,
        "category": "fiction",
        "isbn": "9780593135204",
        "publication_date": date(2021, 5, 4),
        "in_stock": True,
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "description": "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house. One evening her husband returns home late and Alicia shoots him five times in the face.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9781250301697",
        "publication_date": date(2019, 2, 5),
        "in_stock": True,
    },
    {
        "title": "The Song of Achilles",
        "author": "Madeline Miller",
        "description": "A tale of gods, kings, immortal fame and the human heart, The Song of Achilles is a dazzling literary feat that brilliantly reimagines Homer's enduring masterwork, The Iliad.",
        "price": 17.99,
        "category": "fiction",
        "isbn": "9780062060624",
        "publication_date": date(2012, 3, 6),
        "in_stock": True,
    },
    {
        "title": "The Night Circus",
        "author": "Erin Morgenstern",
        "description": "The circus arrives without warning. It is simply there, when yesterday it was not. Within the black-and-white striped canvas tents is an utterly unique experience full of breathtaking amazements.",
        "price": 16.00,
        "category": "fiction",
        "isbn": "9780307744432",
        "publication_date": date(2011, 9, 13),
        "in_stock": True,
    },
    {
        "title": "Circe",
        "author": "Madeline Miller",
        "description": "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother.",
        "price": 17.00,
        "category": "fiction",
        "isbn": "9780316556347",
        "publication_date": date(2018, 4, 10),
        "in_stock": True,
    },
    # Non-Fiction Books
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear reveals practical strategies that will teach you exactly how to form good habits.",
        "price": 27.00,
        "category": "nonfiction",
        "isbn": "9780735211292",
        "publication_date": date(2018, 10, 16),
        "in_stock": True,
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "description": "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
        "price": 18.00,
        "category": "nonfiction",
        "isbn": "9780399590504",
        "publication_date": date(2018, 2, 20),
        "in_stock": True,
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "description": "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us.",
        "price": 24.99,
        "category": "nonfiction",
        "isbn": "9780062316097",
        "publication_date": date(2015, 2, 10),
        "in_stock": True,
    },
    {
        "title": "The Body Keeps the Score",
        "author": "Bessel van der Kolk",
        "description": "Trauma is a fact of life. Veterans and their families deal with the painful aftermath of combat; one in five Americans has been molested; one in four grew up with alcoholics.",
        "price": 19.00,
        "category": "nonfiction",
        "isbn": "9780143127741",
        "publication_date": date(2015, 9, 8),
        "in_stock": True,
    },
    {
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "description": "In this work, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.",
        "price": 20.00,
        "category": "nonfiction",
        "isbn": "9780374533557",
        "publication_date": date(2011, 10, 25),
        "in_stock": True,
    },
    {
        "title": "Becoming",
        "author": "Michelle Obama",
        "description": "In her memoir, a work of deep reflection and mesmerizing storytelling, Michelle Obama invites readers into her world, chronicling the experiences that have shaped her.",
        "price": 32.50,
        "category": "nonfiction",
        "isbn": "9781524763138",
        "publication_date": date(2018, 11, 13),
        "in_stock": True,
    },
    {
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "description": "In The Power of Habit, award-winning business reporter Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed.",
        "price": 17.00,
        "category": "nonfiction",
        "isbn": "9780812981605",
        "publication_date": date(2012, 2, 28),
        "in_stock": True,
    },
    {
        "title": "The Immortal Life of Henrietta Lacks",
        "author": "Rebecca Skloot",
        "description": "Her name was Henrietta Lacks, but scientists know her as HeLa. She was a poor Southern tobacco farmer whose cells—taken without her knowledge—became one of the most important tools in medicine.",
        "price": 16.00,
        "category": "nonfiction",
        "isbn": "9781400052189",
        "publication_date": date(2010, 2, 2),
        "in_stock": True,
    },
    # Teens/Kids Books
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "description": "Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780590353427",
        "publication_date": date(1998, 9, 1),
        "in_stock": True,
    },
    {
        "title": "Percy Jackson and the Lightning Thief",
        "author": "Rick Riordan",
        "description": "Percy Jackson is about to be kicked out of boarding school...again. And that's the least of his troubles. Lately, mythological monsters and the gods of Mount Olympus seem to be walking straight out of the pages of Percy's Greek mythology textbook.",
        "price": 9.99,
        "category": "teens_kids",
        "isbn": "9780786838653",
        "publication_date": date(2005, 7, 1),
        "in_stock": True,
    },
    {
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "description": "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl to participate in the annual Hunger Games.",
        "price": 14.99,
        "category": "teens_kids",
        "isbn": "9780439023481",
        "publication_date": date(2008, 9, 14),
        "in_stock": True,
    },
    {
        "title": "Wonder",
        "author": "R.J. Palacio",
        "description": "August Pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. Starting 5th grade at Beecher Prep, he wants nothing more than to be treated as an ordinary kid.",
        "price": 16.99,
        "category": "teens_kids",
        "isbn": "9780375869020",
        "publication_date": date(2012, 2, 14),
        "in_stock": True,
    },
    {
        "title": "The Giver",
        "author": "Lois Lowry",
        "description": "Jonas's world is perfect. Everything is under control. There is no war or fear or pain. There are no choices. Until Jonas is given his life assignment as the Receiver of Memory.",
        "price": 10.99,
        "category": "teens_kids",
        "isbn": "9780544336261",
        "publication_date": date(1993, 4, 26),
        "in_stock": True,
    },
    {
        "title": "Diary of a Wimpy Kid",
        "author": "Jeff Kinney",
        "description": "Being a kid can really stink. And no one knows this better than Greg Heffley, who finds himself thrust into middle school, where undersized weaklings share the hallways with kids who are taller, meaner, and already shaving.",
        "price": 13.95,
        "category": "teens_kids",
        "isbn": "9780810993136",
        "publication_date": date(2007, 4, 1),
        "in_stock": True,
    },
    {
        "title": "The Maze Runner",
        "author": "James Dashner",
        "description": "When Thomas wakes up in the lift, the only thing he can remember is his name. He's surrounded by strangers—boys whose memories are also gone. Outside the towering stone walls that surround them is a limitless, ever-changing maze.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780385737951",
        "publication_date": date(2009, 10, 6),
        "in_stock": True,
    },
    {
        "title": "Divergent",
        "author": "Veronica Roth",
        "description": "In Beatrice Prior's dystopian Chicago world, society is divided into five factions, each dedicated to the cultivation of a particular virtue. On an appointed day of every year, all sixteen-year-olds must select the faction to which they will devote the rest of their lives.",
        "price": 11.99,
        "category": "teens_kids",
        "isbn": "9780062024022",
        "publication_date": date(2011, 4, 25),
        "in_stock": True,
    },
    # Audiobooks
    {
        "title": "Dune (Audiobook)",
        "author": "Frank Herbert",
        "description": 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.',
        "price": 29.99,
        "category": "audiobook",
        "isbn": "9780593201633",
        "publication_date": date(2020, 10, 5),
        "in_stock": True,
    },
    {
        "title": "The Hobbit (Audiobook)",
        "author": "J.R.R. Tolkien",
        "description": "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep.",
        "price": 24.99,
        "category": "audiobook",
        "isbn": "9780593104415",
        "publication_date": date(2012, 9, 18),
        "in_stock": True,
    },
    {
        "title": "Born a Crime (Audiobook)",
        "author": "Trevor Noah",
        "description": "Trevor Noah's unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison.",
        "price": 22.99,
        "category": "audiobook",
        "isbn": "9781524778569",
        "publication_date": date(2016, 11, 15),
        "in_stock": True,
    },
    {
        "title": "Greenlights (Audiobook)",
        "author": "Matthew McConaughey",
        "description": "From the Academy Award-winning actor, an unconventional memoir filled with raucous stories, outlaw wisdom, and lessons learned the hard way about living with greater satisfaction.",
        "price": 28.00,
        "category": "audiobook",
        "isbn": "9780593139134",
        "publication_date": date(2020, 10, 20),
        "in_stock": True,
    },
    {
        "title": "1984 (Audiobook)",
        "author": "George Orwell",
        "description": "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real.",
        "price": 19.99,
        "category": "audiobook",
        "isbn": "9780147524393",
        "publication_date": date(2013, 6, 4),
        "in_stock": True,
    },
    {
        "title": "The Alchemist (Audiobook)",
        "author": "Paulo Coelho",
        "description": "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
        "price": 21.99,
        "category": "audiobook",
        "isbn": "9780062390622",
        "publication_date": date(2015, 4, 7),
        "in_stock": True,
    },
    {
        "title": "The Martian (Audiobook)",
        "author": "Andy Weir",
        "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm forces his crew to evacuate the planet, Mark finds himself stranded and completely alone.",
        "price": 26.99,
        "category": "audiobook",
        "isbn": "9780804189552",
        "publication_date": date(2014, 2, 11),
        "in_stock": True,
    },
    {
        "title": "Harry Potter and the Prisoner of Azkaban (Audiobook)",
        "author": "J.K. Rowling",
        "description": "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.",
        "price": 32.99,
        "category": "audiobook",
        "isbn": "9780307283672",
        "publication_date": date(2004, 5, 1),
        "in_stock": True,
    },
]

# Create books
created_count = 0
for book_data in books_data:
    book = Book.objects.create(**book_data)
    created_count += 1
    print(f"Created: {book.title} by {book.author}")

print(f"\n✓ Successfully created {created_count} books!")
print(f"  - Fiction: {Book.objects.filter(category='fiction').count()}")
print(f"  - Non-Fiction: {Book.objects.filter(category='nonfiction').count()}")
print(f"  - Teens/Kids: {Book.objects.filter(category='teens_kids').count()}")
print(f"  - Audiobooks: {Book.objects.filter(category='audiobook').count()}")
