"""
Script to populate the database with mock book data for Burt's Bookshelf.
"""

from datetime import date
from typing import Any, Dict, Set


# Mock book data
BOOKS_DATA = [
    # Fiction Books
    {
        "title": "The Midnight Library",
        "author": "Matt Haig",
        "description": "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780525559474",
        "publication_date": date(2020, 8, 13),
        "in_stock": True,
        "cover_image": "https://m.media-amazon.com/images/I/71aiTCR69YS._AC_UF1000,1000_QL80_.jpg",
    },
    {
        "title": "Where the Crawdads Sing",
        "author": "Delia Owens",
        "description": 'For years, rumors of the "Marsh Girl" have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark.',
        "price": 15.99,
        "category": "fiction",
        "isbn": "9780735219090",
        "publication_date": date(2018, 8, 14),
        "in_stock": True,
    },
    {
        "title": "The Seven Husbands of Evelyn Hugo",
        "author": "Taylor Jenkins Reid",
        "description": "Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.",
        "price": 17.99,
        "category": "fiction",
        "isbn": "9781501161933",
        "publication_date": date(2017, 6, 13),
        "in_stock": True,
    },
    {
        "title": "Project Hail Mary",
        "author": "Andy Weir",
        "description": "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.",
        "price": 18.99,
        "category": "fiction",
        "isbn": "9780593135204",
        "publication_date": date(2021, 5, 4),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597695864i/54493401.jpg",
    },
    {
        "title": "The Silent Patient",
        "author": "Alex Michaelides",
        "description": "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house. One evening her husband returns home late and Alicia shoots him five times in the face.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9781250301697",
        "publication_date": date(2019, 2, 5),
        "in_stock": True,
    },
    {
        "title": "The Song of Achilles",
        "author": "Madeline Miller",
        "description": "A tale of gods, kings, immortal fame and the human heart, The Song of Achilles is a dazzling literary feat that brilliantly reimagines Homer's enduring masterwork, The Iliad.",
        "price": 17.99,
        "category": "fiction",
        "isbn": "9780062060624",
        "publication_date": date(2012, 3, 6),
        "in_stock": True,
    },
    {
        "title": "The Night Circus",
        "author": "Erin Morgenstern",
        "description": "The circus arrives without warning. It is simply there, when yesterday it was not. Within the black-and-white striped canvas tents is an utterly unique experience full of breathtaking amazements.",
        "price": 16.00,
        "category": "fiction",
        "isbn": "9780307744432",
        "publication_date": date(2011, 9, 13),
        "in_stock": True,
        "cover_image": "https://www.literarytraveler.com/wp-content/uploads/2013/12/night-circus.jpg",
    },
    {
        "title": "Circe",
        "author": "Madeline Miller",
        "description": "In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother.",
        "price": 17.00,
        "category": "fiction",
        "isbn": "9780316556347",
        "publication_date": date(2018, 4, 10),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1565909496i/35959740.jpg",
    },
    # Non-Fiction Books
    {
        "title": "Atomic Habits",
        "author": "James Clear",
        "description": "No matter your goals, Atomic Habits offers a proven framework for improving—every day. James Clear reveals practical strategies that will teach you exactly how to form good habits.",
        "price": 27.00,
        "category": "nonfiction",
        "isbn": "9780735211292",
        "publication_date": date(2018, 10, 16),
        "in_stock": True,
        "cover_image": "https://m.media-amazon.com/images/I/81YkqyaFVEL._AC_UF1000,1000_QL80_.jpg",
    },
    {
        "title": "Educated",
        "author": "Tara Westover",
        "description": "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
        "price": 18.00,
        "category": "nonfiction",
        "isbn": "9780399590504",
        "publication_date": date(2018, 2, 20),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg",
    },
    {
        "title": "Sapiens: A Brief History of Humankind",
        "author": "Yuval Noah Harari",
        "description": "From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us.",
        "price": 24.99,
        "category": "nonfiction",
        "isbn": "9780062316097",
        "publication_date": date(2015, 2, 10),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1703329310i/23692271.jpg",
    },
    {
        "title": "The Body Keeps the Score",
        "author": "Bessel van der Kolk",
        "description": "Trauma is a fact of life. Veterans and their families deal with the painful aftermath of combat; one in five Americans has been molested; one in four grew up with alcoholics.",
        "price": 19.00,
        "category": "nonfiction",
        "isbn": "9780143127741",
        "publication_date": date(2015, 9, 8),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1594559067i/18693771.jpg",
    },
    {
        "title": "Thinking, Fast and Slow",
        "author": "Daniel Kahneman",
        "description": "In this work, Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.",
        "price": 20.00,
        "category": "nonfiction",
        "isbn": "9780374533557",
        "publication_date": date(2011, 10, 25),
        "in_stock": True,
    },
    {
        "title": "The Shining",
        "author": "Stephen King",
        "description": "Jack Torrance's new job at the Overlook Hotel is the perfect chance for a fresh start. As the off-season caretaker at the atmospheric old hotel, he'll have plenty of time to spend reconnecting with his family and working on his writing. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister.",
        "price": 18.99,
        "category": "fiction",
        "isbn": "9780307743657",
        "publication_date": date(1977, 1, 28),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1353277730i/11588.jpg",
    },
    {
        "title": "The Power of Habit",
        "author": "Charles Duhigg",
        "description": "In The Power of Habit, award-winning business reporter Charles Duhigg takes us to the thrilling edge of scientific discoveries that explain why habits exist and how they can be changed.",
        "price": 17.00,
        "category": "nonfiction",
        "isbn": "9780812981605",
        "publication_date": date(2012, 2, 28),
        "in_stock": True,
    },
    {
        "title": "The Immortal Life of Henrietta Lacks",
        "author": "Rebecca Skloot",
        "description": "Her name was Henrietta Lacks, but scientists know her as HeLa. She was a poor Southern tobacco farmer whose cells—taken without her knowledge—became one of the most important tools in medicine.",
        "price": 16.00,
        "category": "nonfiction",
        "isbn": "9781400052189",
        "publication_date": date(2010, 2, 2),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327878144i/6493208.jpg",
    },
    # Teens/Kids Books
    {
        "title": "Harry Potter and the Sorcerer's Stone",
        "author": "J.K. Rowling",
        "description": "Harry Potter has never been the star of a Quidditch team, scoring points while riding a broom far above the ground. He knows no spells, has never helped to hatch a dragon, and has never worn a cloak of invisibility.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780590353427",
        "publication_date": date(1998, 9, 1),
        "in_stock": True,
    },
    {
        "title": "Percy Jackson and the Lightning Thief",
        "author": "Rick Riordan",
        "description": "Percy Jackson is about to be kicked out of boarding school...again. And that's the least of his troubles. Lately, mythological monsters and the gods of Mount Olympus seem to be walking straight out of the pages of Percy's Greek mythology textbook.",
        "price": 9.99,
        "category": "teens_kids",
        "isbn": "9780786838653",
        "publication_date": date(2005, 7, 1),
        "in_stock": True,
    },
    {
        "title": "The Hunger Games",
        "author": "Suzanne Collins",
        "description": "In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts. The Capitol is harsh and cruel and keeps the districts in line by forcing them all to send one boy and one girl to participate in the annual Hunger Games.",
        "price": 14.99,
        "category": "teens_kids",
        "isbn": "9780439023481",
        "publication_date": date(2008, 9, 14),
        "in_stock": True,
    },
    {
        "title": "Wonder",
        "author": "R.J. Palacio",
        "description": "August Pullman was born with a facial difference that, up until now, has prevented him from going to a mainstream school. Starting 5th grade at Beecher Prep, he wants nothing more than to be treated as an ordinary kid.",
        "price": 16.99,
        "category": "teens_kids",
        "isbn": "9780375869020",
        "publication_date": date(2012, 2, 14),
        "in_stock": True,
    },
    {
        "title": "The Giver",
        "author": "Lois Lowry",
        "description": "Jonas's world is perfect. Everything is under control. There is no war or fear or pain. There are no choices. Until Jonas is given his life assignment as the Receiver of Memory.",
        "price": 10.99,
        "category": "teens_kids",
        "isbn": "9780544336261",
        "publication_date": date(1993, 4, 26),
        "in_stock": True,
    },
    {
        "title": "Diary of a Wimpy Kid",
        "author": "Jeff Kinney",
        "description": "Being a kid can really stink. And no one knows this better than Greg Heffley, who finds himself thrust into middle school, where undersized weaklings share the hallways with kids who are taller, meaner, and already shaving.",
        "price": 13.95,
        "category": "teens_kids",
        "isbn": "9780810993136",
        "publication_date": date(2007, 4, 1),
        "in_stock": True,
        "cover_image": "https://cdn.kobo.com/book-images/69327895-ab7d-45e0-a8a2-7956cf72091a/1200/1200/False/diary-of-a-wimpy-kid-diary-of-a-wimpy-kid-1.jpg",
    },
    {
        "title": "The Maze Runner",
        "author": "James Dashner",
        "description": "When Thomas wakes up in the lift, the only thing he can remember is his name. He's surrounded by strangers—boys whose memories are also gone. Outside the towering stone walls that surround them is a limitless, ever-changing maze.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780385737951",
        "publication_date": date(2009, 10, 6),
        "in_stock": True,
    },
    {
        "title": "Divergent",
        "author": "Veronica Roth",
        "description": "In Beatrice Prior's dystopian Chicago world, society is divided into five factions, each dedicated to the cultivation of a particular virtue. On an appointed day of every year, all sixteen-year-olds must select the faction to which they will devote the rest of their lives.",
        "price": 11.99,
        "category": "teens_kids",
        "isbn": "9780062024022",
        "publication_date": date(2011, 4, 25),
        "in_stock": True,
    },
    # Audiobooks
    {
        "title": "Dune (Audiobook)",
        "author": "Frank Herbert",
        "description": 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the "spice" melange.',
        "price": 29.99,
        "category": "audiobook",
        "isbn": "9780593201633",
        "publication_date": date(2020, 10, 5),
        "in_stock": True,
    },
    {
        "title": "The Hobbit (Audiobook)",
        "author": "J.R.R. Tolkien",
        "description": "Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep.",
        "price": 24.99,
        "category": "audiobook",
        "isbn": "9780593104415",
        "publication_date": date(2012, 9, 18),
        "in_stock": True,
    },
    {
        "title": "Born a Crime (Audiobook)",
        "author": "Trevor Noah",
        "description": "Trevor Noah's unlikely path from apartheid South Africa to the desk of The Daily Show began with a criminal act: his birth. Born to a white Swiss father and a black Xhosa mother at a time when such a union was punishable by five years in prison.",
        "price": 22.99,
        "category": "audiobook",
        "isbn": "9781524778569",
        "publication_date": date(2016, 11, 15),
        "in_stock": True,
    },
    {
        "title": "Greenlights (Audiobook)",
        "author": "Matthew McConaughey",
        "description": "From the Academy Award-winning actor, an unconventional memoir filled with raucous stories, outlaw wisdom, and lessons learned the hard way about living with greater satisfaction.",
        "price": 28.00,
        "category": "audiobook",
        "isbn": "9780593139134",
        "publication_date": date(2020, 10, 20),
        "in_stock": True,
    },
    {
        "title": "1984 (Audiobook)",
        "author": "George Orwell",
        "description": "Among the seminal texts of the 20th century, Nineteen Eighty-Four is a rare work that grows more haunting as its futuristic purgatory becomes more real.",
        "price": 19.99,
        "category": "audiobook",
        "isbn": "9780147524393",
        "publication_date": date(2013, 6, 4),
        "in_stock": True,
        "cover_image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256i/61439040.jpg",
    },
    {
        "title": "The Alchemist (Audiobook)",
        "author": "Paulo Coelho",
        "description": "Paulo Coelho's masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure.",
        "price": 21.99,
        "category": "audiobook",
        "isbn": "9780062390622",
        "publication_date": date(2015, 4, 7),
        "in_stock": True,
    },
    {
        "title": "The Martian (Audiobook)",
        "author": "Andy Weir",
        "description": "Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he's sure he'll be the first person to die there. After a dust storm forces his crew to evacuate the planet, Mark finds himself stranded and completely alone.",
        "price": 26.99,
        "category": "audiobook",
        "isbn": "9780804189552",
        "publication_date": date(2014, 2, 11),
        "in_stock": True,
    },
    {
        "title": "Harry Potter and the Prisoner of Azkaban (Audiobook)",
        "author": "J.K. Rowling",
        "description": "For twelve long years, the dread fortress of Azkaban held an infamous prisoner named Sirius Black. Convicted of killing thirteen people with a single curse, he was said to be the heir apparent to the Dark Lord, Voldemort.",
        "price": 32.99,
        "category": "audiobook",
        "isbn": "9780307283672",
        "publication_date": date(2004, 5, 1),
        "in_stock": True,
    },
    # Toys & Games
    {
        "title": "Codenames Board Game",
        "author": "Czech Games Edition",
        "description": "Two rival spymasters know the secret identities of 25 agents. Their teammates know the agents only by their codenames. The teams compete to see who can make contact with all of their agents first.",
        "price": 19.99,
        "category": "toys_games",
        "isbn": "8594156310318",
        "publication_date": date(2015, 8, 1),
        "in_stock": True,
    },
    {
        "title": "Ticket to Ride Board Game",
        "author": "Days of Wonder",
        "description": "With elegantly simple gameplay, Ticket to Ride can be learned in under 15 minutes. Players collect cards of various types of train cars they then use to claim railway routes in North America.",
        "price": 49.99,
        "category": "toys_games",
        "isbn": "8243100005234",
        "publication_date": date(2004, 6, 1),
        "in_stock": True,
    },
    {
        "title": "Catan Board Game",
        "author": "Catan Studio",
        "description": "Picture yourself in the era of discoveries: after a long voyage of great deprivation, your ships have finally reached the coast of an uncharted island. Its name shall be Catan!",
        "price": 44.99,
        "category": "toys_games",
        "isbn": "0029877030712",
        "publication_date": date(1995, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Pandemic Board Game",
        "author": "Z-Man Games",
        "description": "As members of an elite disease control team, you must work together to stop outbreaks and develop cures before the diseases overwhelm the world with ever-increasing outbreaks.",
        "price": 39.99,
        "category": "toys_games",
        "isbn": "8435407629929",
        "publication_date": date(2008, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Wingspan Board Game",
        "author": "Stonemaier Games",
        "description": "You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves.",
        "price": 59.99,
        "category": "toys_games",
        "isbn": "0644216627790",
        "publication_date": date(2019, 3, 1),
        "in_stock": True,
    },
    {
        "title": "Azul Board Game",
        "author": "Plan B Games",
        "description": "Introduced by the Moors, azulejos (originally white and blue ceramic tiles) were fully embraced by the Portuguese. Embellish the walls of the Royal Palace of Evora!",
        "price": 34.99,
        "category": "toys_games",
        "isbn": "8435407626218",
        "publication_date": date(2017, 10, 1),
        "in_stock": True,
    },
    {
        "title": "Exploding Kittens Card Game",
        "author": "Exploding Kittens",
        "description": "A card game for people who are into kittens and explosions and laser beams and sometimes goats. This is the most-backed project in Kickstarter history.",
        "price": 19.99,
        "category": "toys_games",
        "isbn": "0852131006006",
        "publication_date": date(2015, 7, 1),
        "in_stock": True,
    },
    {
        "title": "Scrabble Classic Board Game",
        "author": "Hasbro Gaming",
        "description": "The classic word game! Form interlocking words on the board. Score points by placing letters on the premium squares. This game features the classic Scrabble gameplay.",
        "price": 24.99,
        "category": "toys_games",
        "isbn": "0630509673919",
        "publication_date": date(1948, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Monopoly Classic Board Game",
        "author": "Hasbro Gaming",
        "description": "The classic fast-dealing property trading game. Players buy, sell, dream and scheme their way to riches. Advance to Boardwalk! Buy property, build houses and hotels!",
        "price": 29.99,
        "category": "toys_games",
        "isbn": "0630509673926",
        "publication_date": date(1935, 1, 1),
        "in_stock": True,
    },
    {
        "title": "UNO Card Game",
        "author": "Mattel Games",
        "description": "When you're down to one card, don't forget to yell 'UNO!' This classic card game matches colors and numbers. Be the first player to get rid of all your cards!",
        "price": 9.99,
        "category": "toys_games",
        "isbn": "0887961141030",
        "publication_date": date(1971, 1, 1),
        "in_stock": True,
    },
    # Additional Fiction Books
    {
        "title": "The Great Gatsby",
        "author": "F. Scott Fitzgerald",
        "description": "The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island.",
        "price": 15.99,
        "category": "fiction",
        "isbn": "9780743273565",
        "publication_date": date(1925, 4, 10),
        "in_stock": True,
    },
    {
        "title": "To Kill a Mockingbird",
        "author": "Harper Lee",
        "description": "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
        "price": 18.99,
        "category": "fiction",
        "isbn": "9780061120084",
        "publication_date": date(1960, 7, 11),
        "in_stock": True,
    },
    {
        "title": "Pride and Prejudice",
        "author": "Jane Austen",
        "description": "A romantic novel of manners that follows the character development of Elizabeth Bennet, the protagonist of the book.",
        "price": 12.99,
        "category": "fiction",
        "isbn": "9780141439518",
        "publication_date": date(1813, 1, 28),
        "in_stock": True,
    },
    {
        "title": "The Catcher in the Rye",
        "author": "J.D. Salinger",
        "description": "The story of teenage rebellion, told through the eyes of Holden Caulfield, a student who has been expelled from prep school.",
        "price": 14.99,
        "category": "fiction",
        "isbn": "9780316769174",
        "publication_date": date(1951, 7, 16),
        "in_stock": True,
    },
    {
        "title": "The Book Thief",
        "author": "Markus Zusak",
        "description": "The story of a young girl living with her adoptive family in Nazi Germany who steals books and shares them with others.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780375842207",
        "publication_date": date(2005, 3, 14),
        "in_stock": True,
    },
    {
        "title": "The Handmaid's Tale",
        "author": "Margaret Atwood",
        "description": "A dystopian novel set in a near-future New England in a patriarchal, totalitarian theonomic state.",
        "price": 15.99,
        "category": "fiction",
        "isbn": "9780385490818",
        "publication_date": date(1985, 6, 1),
        "in_stock": True,
    },
    {
        "title": "The Kite Runner",
        "author": "Khaled Hosseini",
        "description": "A powerful story of friendship between two boys from different social classes in Afghanistan.",
        "price": 17.99,
        "category": "fiction",
        "isbn": "9781594631931",
        "publication_date": date(2003, 5, 29),
        "in_stock": True,
    },
    {
        "title": "Life of Pi",
        "author": "Yann Martel",
        "description": "A young man survives a disaster at sea and is hurtled into an epic journey of adventure and discovery.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780156027328",
        "publication_date": date(2001, 9, 11),
        "in_stock": True,
    },
    {
        "title": "The Fault in Our Stars",
        "author": "John Green",
        "description": "A love story about two teens with cancer who meet at a support group.",
        "price": 14.99,
        "category": "fiction",
        "isbn": "9780525478812",
        "publication_date": date(2012, 1, 10),
        "in_stock": True,
    },
    {
        "title": "Gone Girl",
        "author": "Gillian Flynn",
        "description": "A thriller about a woman who disappears on her fifth wedding anniversary.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780307588371",
        "publication_date": date(2012, 6, 5),
        "in_stock": True,
    },
    {
        "title": "The Girl on the Train",
        "author": "Paula Hawkins",
        "description": "A psychological thriller about a woman who becomes entangled in a missing persons investigation.",
        "price": 15.99,
        "category": "fiction",
        "isbn": "9781594633669",
        "publication_date": date(2015, 1, 13),
        "in_stock": True,
    },
    {
        "title": "Big Little Lies",
        "author": "Liane Moriarty",
        "description": "Three women's seemingly perfect lives unravel to the point of murder.",
        "price": 16.99,
        "category": "fiction",
        "isbn": "9780399167065",
        "publication_date": date(2014, 7, 29),
        "in_stock": True,
    },
    # Additional Non-Fiction Books
    {
        "title": "Becoming",
        "author": "Michelle Obama",
        "description": "The memoir of the former First Lady of the United States.",
        "price": 19.99,
        "category": "nonfiction",
        "isbn": "9781524763138",
        "publication_date": date(2018, 11, 13),
        "in_stock": True,
    },
    {
        "title": "The Subtle Art of Not Giving a F*ck",
        "author": "Mark Manson",
        "description": "A counterintuitive approach to living a good life.",
        "price": 16.99,
        "category": "nonfiction",
        "isbn": "9780062457714",
        "publication_date": date(2016, 9, 13),
        "in_stock": True,
    },
    {
        "title": "Steve Jobs",
        "author": "Walter Isaacson",
        "description": "The exclusive biography of Steve Jobs based on more than forty interviews with Jobs.",
        "price": 20.99,
        "category": "nonfiction",
        "isbn": "9781451648539",
        "publication_date": date(2011, 10, 24),
        "in_stock": True,
    },
    {
        "title": "Bad Blood",
        "author": "John Carreyrou",
        "description": "The full inside story of the breathtaking rise and shocking collapse of Theranos.",
        "price": 18.99,
        "category": "nonfiction",
        "isbn": "9781524731656",
        "publication_date": date(2018, 5, 21),
        "in_stock": True,
    },
    {
        "title": "When Breath Becomes Air",
        "author": "Paul Kalanithi",
        "description": "A neurosurgeon's memoir about facing terminal cancer.",
        "price": 17.99,
        "category": "nonfiction",
        "isbn": "9780812988406",
        "publication_date": date(2016, 1, 12),
        "in_stock": True,
    },
    {
        "title": "The Power of Now",
        "author": "Eckhart Tolle",
        "description": "A guide to spiritual enlightenment that shows how to live in the present moment.",
        "price": 16.99,
        "category": "nonfiction",
        "isbn": "9781577314806",
        "publication_date": date(1997, 8, 1),
        "in_stock": True,
    },
    {
        "title": "Born to Run",
        "author": "Christopher McDougall",
        "description": "A hidden tribe, superathletes, and the greatest race the world has never seen.",
        "price": 17.99,
        "category": "nonfiction",
        "isbn": "9780307279187",
        "publication_date": date(2009, 5, 5),
        "in_stock": True,
    },
    {
        "title": "Quiet",
        "author": "Susan Cain",
        "description": "The power of introverts in a world that can't stop talking.",
        "price": 18.99,
        "category": "nonfiction",
        "isbn": "9780307352156",
        "publication_date": date(2012, 1, 24),
        "in_stock": True,
    },
    {
        "title": "Outliers",
        "author": "Malcolm Gladwell",
        "description": "The story of success and what makes high-achievers different.",
        "price": 17.99,
        "category": "nonfiction",
        "isbn": "9780316017930",
        "publication_date": date(2008, 11, 18),
        "in_stock": True,
    },
    {
        "title": "The 7 Habits of Highly Effective People",
        "author": "Stephen R. Covey",
        "description": "Powerful lessons in personal change.",
        "price": 19.99,
        "category": "nonfiction",
        "isbn": "9781982137274",
        "publication_date": date(1989, 8, 15),
        "in_stock": True,
    },
    # Additional Teens/Kids Books
    {
        "title": "The Lightning Thief",
        "author": "Rick Riordan",
        "description": "Percy Jackson discovers he's a demigod and must prevent a war between the Greek gods.",
        "price": 14.99,
        "category": "teens_kids",
        "isbn": "9780786838653",
        "publication_date": date(2005, 7, 1),
        "in_stock": True,
    },
    {
        "title": "Charlotte's Web",
        "author": "E.B. White",
        "description": "The story of a pig named Wilbur and his friendship with a barn spider named Charlotte.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780064400558",
        "publication_date": date(1952, 10, 15),
        "in_stock": True,
    },
    {
        "title": "Matilda",
        "author": "Roald Dahl",
        "description": "The story of an extraordinary girl with a vivid imagination and a sharp mind.",
        "price": 13.99,
        "category": "teens_kids",
        "isbn": "9780142410370",
        "publication_date": date(1988, 10, 1),
        "in_stock": True,
    },
    {
        "title": "The Chronicles of Narnia",
        "author": "C.S. Lewis",
        "description": "Four children discover a magical world through a wardrobe.",
        "price": 19.99,
        "category": "teens_kids",
        "isbn": "9780066238500",
        "publication_date": date(1950, 10, 16),
        "in_stock": True,
    },
    {
        "title": "A Wrinkle in Time",
        "author": "Madeleine L'Engle",
        "description": "A young girl journeys through space and time to rescue her father.",
        "price": 13.99,
        "category": "teens_kids",
        "isbn": "9780312367541",
        "publication_date": date(1962, 1, 1),
        "in_stock": True,
    },
    {
        "title": "The Secret Garden",
        "author": "Frances Hodgson Burnett",
        "description": "A young orphan discovers a magical garden at her uncle's estate.",
        "price": 11.99,
        "category": "teens_kids",
        "isbn": "9780064401883",
        "publication_date": date(1911, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Bridge to Terabithia",
        "author": "Katherine Paterson",
        "description": "Two friends create a magical kingdom in the woods.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780064401845",
        "publication_date": date(1977, 10, 21),
        "in_stock": True,
    },
    {
        "title": "Holes",
        "author": "Louis Sachar",
        "description": "A boy is sent to a desert detention camp where he must dig holes every day.",
        "price": 13.99,
        "category": "teens_kids",
        "isbn": "9780440228592",
        "publication_date": date(1998, 8, 20),
        "in_stock": True,
    },
    {
        "title": "The Tale of Despereaux",
        "author": "Kate DiCamillo",
        "description": "The story of a brave mouse who falls in love with a princess.",
        "price": 12.99,
        "category": "teens_kids",
        "isbn": "9780763625290",
        "publication_date": date(2003, 8, 25),
        "in_stock": True,
    },
    {
        "title": "Where the Wild Things Are",
        "author": "Maurice Sendak",
        "description": "A boy named Max sails away to an island inhabited by wild creatures.",
        "price": 10.99,
        "category": "teens_kids",
        "isbn": "9780060254926",
        "publication_date": date(1963, 11, 13),
        "in_stock": True,
    },
    # Additional Audiobooks
    {
        "title": "Becoming (Audiobook)",
        "author": "Michelle Obama",
        "description": "The audiobook narrated by the author herself, sharing her deeply personal story.",
        "price": 24.99,
        "category": "audiobook",
        "isbn": "9780525633662",
        "publication_date": date(2018, 11, 13),
        "in_stock": True,
    },
    {
        "title": "The Subtle Art of Not Giving a F*ck (Audiobook)",
        "author": "Mark Manson",
        "description": "An entertaining audiobook about choosing what truly matters in your life.",
        "price": 19.99,
        "category": "audiobook",
        "isbn": "9780062457738",
        "publication_date": date(2016, 9, 13),
        "in_stock": True,
    },
    {
        "title": "Where the Crawdads Sing (Audiobook)",
        "author": "Delia Owens",
        "description": "A haunting audiobook of mystery, survival, and the places we call home.",
        "price": 22.99,
        "category": "audiobook",
        "isbn": "9780735219113",
        "publication_date": date(2018, 8, 14),
        "in_stock": True,
    },
    {
        "title": "Educated (Audiobook)",
        "author": "Tara Westover",
        "description": "A memoir audiobook about a young woman who leaves her survivalist family.",
        "price": 21.99,
        "category": "audiobook",
        "isbn": "9780525589983",
        "publication_date": date(2018, 2, 20),
        "in_stock": True,
    },
    {
        "title": "The Great Gatsby (Audiobook)",
        "author": "F. Scott Fitzgerald",
        "description": "The classic American novel in audiobook format.",
        "price": 18.99,
        "category": "audiobook",
        "isbn": "9780743565776",
        "publication_date": date(1925, 4, 10),
        "in_stock": True,
    },
    # Additional Toys & Games
    {
        "title": "Chess Set Classic",
        "author": "Various",
        "description": "A classic wooden chess set with beautifully crafted pieces.",
        "price": 39.99,
        "category": "toys_games",
        "isbn": "0794850012345",
        "publication_date": date(2020, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Clue Board Game",
        "author": "Hasbro Gaming",
        "description": "The classic detective game. Can you solve the mystery?",
        "price": 24.99,
        "category": "toys_games",
        "isbn": "0630509867234",
        "publication_date": date(1949, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Risk Strategy Game",
        "author": "Hasbro Gaming",
        "description": "The game of strategic conquest. Take over the world!",
        "price": 34.99,
        "category": "toys_games",
        "isbn": "0630509456789",
        "publication_date": date(1959, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Jenga Classic Game",
        "author": "Hasbro Gaming",
        "description": "Stack the blocks, build the tower, don't let it fall!",
        "price": 19.99,
        "category": "toys_games",
        "isbn": "0630509234567",
        "publication_date": date(1983, 1, 1),
        "in_stock": True,
    },
    {
        "title": "Connect 4 Game",
        "author": "Hasbro Gaming",
        "description": "Choose your color, drop your checker, and get four in a row to win!",
        "price": 14.99,
        "category": "toys_games",
        "isbn": "0630509345678",
        "publication_date": date(1974, 1, 1),
        "in_stock": True,
    },
]

CATEGORY_LABELS: Dict[str, str] = {
    "fiction": "Fiction",
    "nonfiction": "Non-Fiction",
    "teens_kids": "Teens/Kids",
    "audiobook": "Audiobooks",
    "toys_games": "Toys & Games",
}


def load_books(*, delete_existing: bool = True) -> Dict[str, Any]:
    """Populate the database with the sample catalog."""
    from django.apps import apps

    Book = apps.get_model("bookstore", "Book")

    if delete_existing:
        Book.objects.all().delete()

    created_count = 0
    updated_count = 0
    duplicate_count = 0
    category_counts: Dict[str, int] = {}
    seen_isbns: Set[str] = set()

    for book_data in BOOKS_DATA:
        book_fields = dict(book_data)
        isbn = book_fields.pop("isbn")

        obj, created = Book.objects.update_or_create(
            isbn=isbn,
            defaults=book_fields,
        )

        if created:
            created_count += 1
        else:
            updated_count += 1
            if isbn in seen_isbns:
                duplicate_count += 1

        if isbn not in seen_isbns:
            category = book_data.get("category", "unknown")
            category_counts[category] = category_counts.get(category, 0) + 1
            seen_isbns.add(isbn)

    return {
        "created": created_count,
        "updated": updated_count,
        "duplicates": duplicate_count,
        "categories": category_counts,
        "total": len(seen_isbns),
    }


if __name__ == "__main__":
    import os
    import django

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "burts_books.settings")
    django.setup()

    summary = load_books(delete_existing=True)

    created = summary.get("created", 0)
    updated = summary.get("updated", 0)
    duplicates = summary.get("duplicates", 0)

    print(f"\n✓ Successfully processed {summary.get('total', created)} books!")
    if created:
        print(f"  - Created: {created}")
    if updated:
        print(f"  - Updated: {updated}")
    if duplicates:
        print(f"  - Duplicates encountered: {duplicates}")

    for key, label in CATEGORY_LABELS.items():
        count = summary["categories"].get(key, 0)
        print(f"  - {label}: {count}")

    extra_categories = {
        key: value
        for key, value in summary["categories"].items()
        if key not in CATEGORY_LABELS
    }
    for key, value in extra_categories.items():
        print(f"  - {key}: {value}")
