# Generated by Django 5.2.8 on 2025-11-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('fiction', 'Fiction'), ('nonfiction', 'Non-Fiction'), ('teens_kids', 'Teens/Kids'), ('audiobook', 'Audiobook')], max_length=20)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('in_stock', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
